name: C/C++ CI

on: [push]

jobs:
  build-windows-22:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
    
    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./generate_cache.bat /22
    
    - name: build
      run: ./build.bat

  build-windows-19:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
    
    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: ./generate_cache.bat /19
    
    - name: build
      run: ./build.bat
